### ISSUE TITLE
生成的模型可以转成dae格式吗

### ISSUE THREAD

**Issue by MayuOshima** [Mansterteddy/SCAPE#1]
你好！我是刚刚接触这方面的东西。想问一下你最后生成的模型可以转成DAE文件吗？如果可以的话该怎么转呢？如果不行的话我需要添加些什么或者进行什么修改吗？谢谢~

**Comment by Mansterteddy** [comment]
Hey，我的程序直接生成obj文件，你可以通过其他3D工具，将obj文件转成DAE文件。
