### ISSUE TITLE
你这里好像没有你所说的scape和SPRING_MALE_2文件夹啊

### ISSUE THREAD

**Issue by MayuOshima** [Mansterteddy/SCAPE#2]
因此MATLAB代码跑不了。。。

**Comment by Mansterteddy** [comment]
抱歉，这些文件夹的内容来自SCAPE数据集，我没有权限分享该数据，需要向scape datasets owner申请数据集，并放在当前文件夹下。

**Comment by MayuOshima** [comment]
原来如此！
事实上我去找那个人要他那个下载的密码了，但是他一直没回复我。
我是上海交大大三cs的一个同学，最近在做一个course project需要用到这个训练后的结果。
你那里有生成的模型的结果吗？我有点着急，因为不知道他什么时候能回复我。
如果有的话可以把generate出来的结果发我一下吗？我需要把结果丢到我写好的另一个模型里跑。
谢谢了！

----- 原始邮件 -----
发件人: "Zhang Yuan" <notifications@github.com>
收件人: "Mansterteddy/SCAPE" <SCAPE@noreply.github.com>
抄送: "Ajin" <magi-yunan@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期二, 2018年 6 月 12日 下午 6:02:31
主题: Re: [Mansterteddy/SCAPE] 你这里好像没有你所说的scape和SPRING_MALE_2文件夹啊 (#2)

抱歉，这些文件夹的内容来自SCAPE数据集，我没有权限分享该数据，需要向scape datasets owner申请数据集，并放在当前文件夹下。

**Comment by MayuOshima** [comment]
啊我收到他的回复了

----- 原始邮件 -----
发件人: "Zhang Yuan" <notifications@github.com>
收件人: "Mansterteddy/SCAPE" <SCAPE@noreply.github.com>
抄送: "Ajin" <magi-yunan@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期二, 2018年 6 月 12日 下午 6:02:31
主题: Re: [Mansterteddy/SCAPE] 你这里好像没有你所说的scape和SPRING_MALE_2文件夹啊 (#2)

抱歉，这些文件夹的内容来自SCAPE数据集，我没有权限分享该数据，需要向scape datasets owner申请数据集，并放在当前文件夹下。

**Comment by Z-Silver-Jun** [comment]
@MayuOshima 你好！
方便发一下scape和SPRING_MALE_2文件夹吗？我也在研究SCAPE项目：）
邮箱：zsilverj@ncepu.edu.cn
感谢！

**Comment by FD-MINGJIE** [comment]
@MayuOshima
@Z-Silver-Jun
大佬，有scape和SPRING_MALE_2数据吗，想深入学习一下，非常感谢，谢谢！
