### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by abbott1234** [Mansterteddy/SCAPE#3]
I have read your past issues, and asked for the dataset form the author. But got no answer. 
So would you give me your trained model for my next step work?

**Comment by Mansterteddy** [comment]
Sorry, I cannot share trained model since it is too large to upload.

**Comment by abbott1234** [comment]
If I have my own obj dataset, what should I do for train my own model?

**Comment by Mansterteddy** [comment]
You can follow procedures in README:

```
trainQ = generateQmatrix()
deltar = generatedeltar()
pose_model = posemodel_training()
U, mu, trainS1 = generateSmatrix()
scapetracking_withoutshape()
scapetracking_shape_pose()
save train pose_model U eigen_value amu
```

**Comment by abbott1234** [comment]
Did you have any extra work for the data, such as label or special work. 
I have tried to use the code with my data, but it raise a error.

**Comment by Mansterteddy** [comment]
You need to make sure that your human model data has same format with SCAPE, e.g. vertex counts.
