### ISSUE TITLE
eigen_value

### ISSUE THREAD

**Issue by abbott1234** [Mansterteddy/SCAPE#4]
’scapetracking_shape_pose’  function need eigen_value variable, but there has no variable call eigen_value before.

**Comment by Mansterteddy** [comment]
You can find related code in generateSmatrix.m.

**Comment by abbott1234** [comment]
Do you mean the variable called eigenvalue which is the return value in function PCA

**Comment by Mansterteddy** [comment]
Yes, you can have a try.
