### ISSUE TITLE
About bodyseg

### ISSUE THREAD

**Issue by linxiaoy** [Mansterteddy/SCAPE#5]
Hello, how do you get bodyseg? If you change the template model, how do get bodyseg? Hope to see your reply

**Comment by Mansterteddy** [comment]
BodySeg is labeled manually.

**Comment by linxiaoy** [comment]
Thanks for your answer！ 

If it is convenient, I would like to ask a few questions. How to get the index of the patch of different body parts? Have you tried using data sets other than SCAPE? For example, the number of vertex and faces are different from SCAPE data sets. Thank you again!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mansterteddy/SCAPE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 中午1:14
收件人:&nbsp;"Mansterteddy/SCAPE"<SCAPE@noreply.github.com&gt;;
抄送:&nbsp;"长青藤"<3035198143@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mansterteddy/SCAPE] About bodyseg (#5)





 
BodySeg is labeled manually.

**Comment by Mansterteddy** [comment]
You can refer Michael Black's work: https://ps.is.mpg.de/~black.

**Comment by linxiaoy** [comment]
Ok, thank you again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mansterteddy/SCAPE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月15日(星期六) 下午2:47
收件人:&nbsp;"Mansterteddy/SCAPE"<SCAPE@noreply.github.com&gt;;
抄送:&nbsp;"长青藤"<3035198143@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mansterteddy/SCAPE] About bodyseg (#5)





 
You can refer Michael Black's work: https://ps.is.mpg.de/~black.
