### ISSUE TITLE
SCAPE dataset

### ISSUE THREAD

**Issue by chenlu233** [Mansterteddy/SCAPE#6]
Excuse me, where is the data set for SCAPE?

**Comment by Mansterteddy** [comment]
Please contact the author.

**Comment by chenlu233** [comment]
我很急需，能不能麻烦您先给我一份。作者还未回复我。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mansterteddy/SCAPE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mansterteddy/SCAPE] SCAPE dataset (#6)





 
Please contact the author.
